### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by JorgeAnzola** [JorgeAnzola/environment-protection#7]
When using a `protected.twig` template Craft will throw the following error below the template (On local)

```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/vendor/jorgeanzola/environment-protection/src/EnvironmentProtection.php on line 78. in /var/www/vendor/yiisoft/yii2/web/Response.php:373
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/Response.php(346): yii\web\Response->sendHeaders()
#1 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(147): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#4 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#5 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
...
```

**Comment by JorgeAnzola** [comment]
![Screenshot 2021-08-11 at 10 51 53](https://user-images.githubusercontent.com/15676614/128999839-8ec243c5-088c-428f-b3fe-6bd8d37f9ae8.jpg)
